applications:
  aws-load-balancer-controller:
    repoURL: https://aws.github.io/eks-charts
    chartName: aws-load-balancer-controller
    chartVersion: 1.4.7
    releaseName: aws-load-balancer-controller
    namespace: alb-ingress
    project: cloud-team
  metrics-server:
    repoURL: https://kubernetes-sigs.github.io/metrics-server
    chartName: metrics-server
    chartVersion: 3.8.3
    releaseName: metrics-server
    namespace: metrics-server
    project: cloud-team
